name: 'Terraform'
on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: terraform/
      env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          AWS_DEFAULT_REGION: "fr-par-1"

    - name: Terraform Format
      working-directory: terraform/
      run: terraform fmt -check

    - name: Terraform Plan dev
      if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
      working-directory: terraform/
      run: terraform plan -input=false -var-file="envs/dev.tfvars"
      env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          AWS_DEFAULT_REGION: "fr-par-1"

    - name: Terraform Plan prd
      if: github.ref == 'refs/heads/prd' && github.event_name == 'push'
      working-directory: terraform/
      run: terraform plan -input=false -var-file="envs/prd.tfvars"
      env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          AWS_DEFAULT_REGION: "fr-par-1"

    - name: Terraform Apply Production
      if: github.ref == 'refs/heads/prd' && github.event_name == 'push'
      working-directory: terraform/
      run: terraform apply -auto-approve -input=false -var-file="envs/prd.tfvars"
      env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          AWS_DEFAULT_REGION: "fr-par-1"

    - name: Terraform Apply dev
      if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
      working-directory: terraform/
      run: terraform apply -auto-approve -input=false -var-file="envs/dev.tfvars"
      env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          AWS_DEFAULT_REGION: "fr-par-1"
    