name: 'Terraform'
on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: terraform/
      env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          AWS_DEFAULT_REGION: "fr-par-1"

    - name: Terraform Format
      working-directory: terraform/
      run: terraform fmt -check

    - name: Set Workspace
      id: set_workspace
      run: |
          echo "::set-output name=environment::`echo ${{ github.ref }} | cut -d \/ -f3`"

    - name: Terraform Plan
      if: github.event_name == 'push'
      working-directory: terraform/
      run: terraform plan -input=false -var-file="envs/${{ steps.set_workspace.outputs.environment }}.tfvars"
      env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          AWS_DEFAULT_REGION: "fr-par-1"
          TF_WORKSPACE: ${{ steps.set_workspace.outputs.environment }}

    - name: Terraform Apply
      if: github.event_name == 'push'
      working-directory: terraform/
      run: terraform apply -auto-approve -input=false -var-file="envs/${{ steps.set_workspace.outputs.environment }}.tfvars"
      env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          AWS_DEFAULT_REGION: "fr-par-1"
          TF_WORKSPACE: ${{ steps.set_workspace.outputs.environment }}
